<!DOCTYPE html>
<html lang=en>
    <head>
        <meta charset=utf-8>
        <meta http-equiv=X-UA-Compatible content="IE=edge">
        <meta name=viewport content="width=device-width,initial-scale=1">
        <link rel=icon href=favicon.ico>
        <title>${title}</title>
    </head>
    <body>
        <noscript>
            <strong>We're sorry but lk doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
        </noscript>
        <form method="POST">
            <input type="text" name="username" value = "" placeholder="Username" autofocus="true">
            <input type="password" name="password" placeholder="Password" value = "">
            <input type="passwordConfirm" name="passwordConfirm" placeholder="Confirm your password" value = "">
            <button type="submit">Зарегистрироваться</button>
        </form>
    </body>
</html>